apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: coordinator
          image: boyapatiakhil7/stressg:0.1
          ports:
            - containerPort: 80
          command: ["/bin/sh","-c"]
          args: ["/root/downloads/stressgrid/coordinator/_build/prod/rel/coordinator/bin/coordinator start"]
          env:
            - name: COORDINATOR_POD_IP
                valueFrom:
                  fieldRef:
                    fieldPath: status.podIP

