apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
  labels:
    app: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  template:
    metadata:
      labels:
        app: generator
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: generator
          image: boyapatiakhil7/stressg:0.1
          resources:
            requests:
              cpu: "2"
              memory: "2.0Gi"
            limits:
              cpu: "4"
              memory: "4.0Gi"
          command: ["/bin/sh","-c"]
          args: ["export COORDINATOR_URL=ws://$COORDINATOR_GEN_SERVICE_SERVICE_HOST:9696 && /root/downloads/stressgrid/generator/_build/prod/rel/generator/bin/generator start"]